# Netlify configuration file

# Settings for your production environment.
# These are used when you deploy to your main production branch.
[build]
  # Directory for build output, relative to the root of your repository.
  # This is where Netlify will look for your site content.
  publish = "dist"     # Change "dist" to your build output folder if it's different

  # Your build command.
  # This is the command that Netlify will run to build your site.
  command = "npm run build"  # Change this to your actual build command if necessary

# Redirects
# Here you define the redirection rules for your site.
[[redirects]]
  from = "/Ourservices.html"
  to = "/about-us"
  status = 301
  force = true

[[redirects]]
  from = "/USA.html"
  to = "/study-usa"
  status = 301
  force = true

[[redirects]]
  from = "/IELTS.html"
  to = "/ielts"
  status = 301
  force = true

[[redirects]]
  from = "/about.html"
  to = "/services"
  status = 301
  force = true

[[redirects]]
  from = "/contact.html"
  to = "/contact-us"
  status = 301
  force = true

[[redirects]]
  from = "/book-consultancy"
  to = "/consultancy"
  status = 301
  force = true

[[redirects]]
  from = "/*"
  to = "/"
  status = 301
  force = true

  [[redirects]]
  from = "/main.js"
  to = "/main.js"
  status = 200